# Generated by Django 4.2.6 on 2023-10-27 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('add', '0004_remove_ad_is_blocked_location_is_blocked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='is_blocked',
        ),
        migrations.AddField(
            model_name='ad',
            name='is_blocked',
            field=models.BooleanField(default=False),
        ),
    ]
