# Generated by Django 4.2.6 on 2023-10-27 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('add', '0006_remove_ad_is_blocked_dailyvisitor_is_blocked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailyvisitor',
            name='is_blocked',
        ),
    ]
