# Generated by Django 4.2.6 on 2023-10-27 19:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('add', '0007_remove_dailyvisitor_is_blocked'),
    ]

    operations = [
        migrations.CreateModel(
            name='vistor_user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
            ],
        ),
        migrations.AddField(
            model_name='dailyvisitor',
            name='vistor',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='add.vistor_user'),
            preserve_default=False,
        ),
    ]
