# Generated by Django 4.2.6 on 2023-10-27 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('add', '0008_vistor_user_dailyvisitor_vistor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyvisitor',
            name='visitor_count',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterUniqueTogether(
            name='dailyvisitor',
            unique_together={('location', 'ad', 'vistor')},
        ),
    ]
