# Generated by Django 4.2.6 on 2023-10-27 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('add', '0010_alter_dailyvisitor_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='is_blocked',
            field=models.BooleanField(default=False),
        ),
    ]
